name: gamejam_template
publish_to: none

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies: 
  angular: ^6.0.1
  aspen: ^0.3.0
  aspen_assets: ^0.4.0
  dartemis: ^0.8.0
  gamedev_helpers:
    git:
      url: git@github.com:kayzgames/gamedev_helpers.git
      ref: aspen040

dev_dependencies:
  aspen_builder: ^0.4.0
  build_runner: ^1.10.4
  build_web_compilers: ^2.13.0
  dartemis_builder: ^0.1.0+1
  sass_builder: ^2.1.3

dependency_overrides:
  aspen_assets:
    path: ../aspen/aspen_assets
  aspen_builder:
    path: ../aspen/aspen_builder